permalink: /:title/
pygments: true
markdown: redcarpet
name: lumberjaph.net
future: false
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
exclude:
  - CNAME
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - Makefile
