This weekend I went to the second edition of the OSDC.fr conference.
This conference is organized by the Python, Ruby, PHP and Perl french
organizations. This edition was really really good, and well organized
(kudo to the whole team!).

The first day of the conference, we had two excellents talk about Git.
The first one by [[http://github.com/mojombo][mojombo]], about
[[http://git-tips.heroku.com/#1][advanced git usages]]. I've managed to
get him to sign my copy of the
[[http://lumberjaph.net/graph/2010/03/25/github-explorer.html][GitHub
poster]]. The second one by BooK was about his module
[[http://search.cpan.org/perldoc?Git::Repository][Git::Repository]]
(which I use for [[http://github.com/franckcuny/jitterbug][jitterbug]]).
He show us how he used git to graph his familly tree.

Germain did an
[[http://www.slideshare.net/franckcuny/riak-a-file-system-for-internet][introduction
to Riak]], and [[http://twitter.com/flngr][Julian]] did a talk about
[[http://gephi.org/][Gephi]], about how it relies on the netbeans
platform, and why a tool to visualize graphs is useful.

I've talked about Plack in the afternoon, and
[[http://sukria.net][sukria]] talked about Dancer right after me. I
think both our talks went well, and his one was a nice demonstration of
Dancer, since he used [[http://github.com/sukria/broadway][Broadway]] to
write his slides. I planned to do some demos during my talk, but a
problem with my laptop prevented me to do this. Anyway, if you attended
my talk and want to try them, here they are :

#+BEGIN_SRC perl
    use strict;
    use warnings;
    use Plack::Builder;

    my $app = sub {
        return [
            200,
            [ 'Content-Type' => 'text/html' ],
            [ '<html><body>Hello World</body></html>' ]
        ];
    };

    builder {
        enable 'Debug';
        $app;
    };
#+END_SRC

#+BEGIN_SRC perl
    use strict;
    use warnings;
    use Plack::Builder;

    my $app1 = sub {[200, ['Content-Type' => 'text/html'], ['hello from app1']]};
    my $app2 = sub {[200, ['Content-Type' => 'text/html'], ['hello from app2']]};

    builder {
        mount "/app1" => $app1;
        mount "/app2" => $app2;
    };
#+END_SRC

#+BEGIN_SRC perl
    use strict;
    use warnings;
    use Plack::Builder;

    my $app = sub { [ 200, [ 'Content-Type' => 'text/html' ], ['hello world'] ] };

    my $middleware = sub {
        my $env = shift;
        my $res = $app->($env);
        $res->[2]->[0] =~ s/world/OSDC.fr/;
        return $res;
    };
#+END_SRC

#+BEGIN_SRC perl
    use strict;
    use warnings;
    use Plack::Builder;

    my $app = sub {
        die "die";
        [ 200, [ 'Content-Type' => 'text/html' ], ['hello world'], ];
    };

    builder {
        enable "StackTrace";
        $app;
    };
#+END_SRC

#+BEGIN_SRC perl
    use strict;
    use warnings;
    use Plack::Builder;

    my $app = sub { return [ '200', [ 'Content-Type' => 'text/html' ], ['hello world'] ] };

    builder {
        enable "Throttle::Hourly", max => 1;
        $app;
    };
#+END_SRC

The evening GitHub offered the beers (yeah!) in a pub, and I had an
intersting talk with [[http://github.com/fperrad][fperrad]] about SPORE.
Francois surprised me earlier last week when he contacted me to announce
me he add write a Lua version of SPORE. He had some questions and
suggestions for the current spec and API, and we managed to handle all
the issues.

The sunday I talked about [[http://github.com/franckcuny/spore][SPORE]].
Even if the talk went not so well, I managed to interest some people,
since I had some questions and positive feedback. I've not seen much
talk the sunday, as I've spent some time with sukria and others to
discuss about code. But I managed to see the talk about Redis which was
good, and gave me some ideas for
[[http://github.com/franckcuny/presque][presque]].

The ligthning talks were also interesting.
[[http://twitter.com/brmichel][Bruno Michel]] talked about
[[http://rubyeventmachine.com/][EventMachine]],
[[http://github.com/htty][htty]] and
[[http://mongrel2.org/home][mongrel2]],
[[http://search.cpan.org/~dolmen/][dolmen]] showed us a small
application to graph a svn repository, and
[[http://search.cpan.org/~book/][BooK]] told us about his work on
[[http://search.cpan.org/perldoc?Devel::TraceUse][Devel::TraceUse]].

I wish I would have been able to attend [[http://twitter.com/ephoz][oz]]
presentation of [[http://cyprio.net/nodejs_osdc.pdf][nodejs]], and I've
also missed the talks given by carl masak, since I was working with
sukria on Dancer at that time.

All the slides for my talks are available:

-  [[https://docs.google.com/presentation/d/1Ty8df3IG44rwHRuBnpgriTHiKREqGN_aIJcABddFIKM/present#slide=id.i0][Plack]]
-  [[https://docs.google.com/presentation/d/1JpDz3F9K41KVFQ878IEFAnHQZ05BpGJz6dpdPi21tjU/present#slide=id.i0][SPORE]]
-  [[https://docs.google.com/presentation/d/1-fpByFQ4OJoe2NE8lMkwl-zbK8OWuLqGA_Y4B4YmFhA/present#slide=id.i0][jitterbug]]
-  [[https://docs.google.com/presentation/d/1Y9TZh9A4an9ctC6mEZcONkx_9z9b66TJ5Lg4awVIoiA/present#slide=id.i0][presque]]
